### ISSUE TITLE
2 CANFD on PIC32MK1024MCM100

### ISSUE THREAD

**Issue by raf6410** [Microchip-MPLAB-Harmony/csp#31]
Hi,

I work on PIC32MK1024MCM100 an CANFD in a custum board.
All CAN channel work correctly alone.
But when I tried to use 2, 3 or 4 CAN in same time PIC CRASH.
I think that the PIC don't start.

Could you help me 

RAF6410

![CANFD_Setup](https://user-images.githubusercontent.com/25167415/121902007-37e36480-cd27-11eb-9225-2e463f115e1c.jpg)

**Comment by jigneshmoradiya1** [comment]
Hi,

Data Bit Timing is not correctly configured for 4000 Kbps Bit Rate because Calculated Bit Rate is 0 and Error % is 100%. CAN-FD Clock Frequency should be configured 20MHz/40MHz/80MHz as per datasheet (https://ww1.microchip.com/downloads/en/DeviceDoc/PIC32MK-GPK-MCM-with-CAN-FD-Family-DataSheet-DS60001519E.pdf, Page#463).
For example, Please find the MHC configuration for CAN-FD clock frequency 20MHz, Nominal Bit Rate 500 Kbps and Data Bit Rate 4000 Kbps as below.
![image](https://user-images.githubusercontent.com/47806476/121916628-f3b98980-cd51-11eb-84e4-984a5266a280.png)

Thank you.

**Comment by raf6410** [comment]
hi,

Thanks for your comment.
I tried to config 2 CAN channel with your proposal => same probleme, PIC don't start.
I use REFCLK4 to 20Mhz but nothing

**Comment by raf6410** [comment]
After many tried, the problem appear only when i add CAN2.
Actually my PIC works with CAN1, CAN3, CAN4 and UART2 ON.

**Comment by jigneshmoradiya1** [comment]
@raf6410 , CAN Bit Timing should be configured in MHC configuration as mentioned in above screenshot. Closing the ticket now. In case of any issue please feel free to reopen ticket.
